# Configuration file example
server:
  host: "localhost"
  port: "8080"

database:
  host: "localhost"
  port: "5432"
  username: "postgres"
  password: "password"
  dbname: "shorten_url_db"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "0"
